### ISSUE TITLE
wwwroot and Views not being published

### ISSUE THREAD

**Issue by oswaldofreitas** [gerardo-lijs/AspNetCoreWindowsService#1]
Hi, thank you for your sample, but after I change framework from netcoreapp1.0 to net461 I don't have any folders (wwwroot, Views) in the bin output folder.

`
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },`

**Comment by gerardo-lijs** [comment]
Hi, I think a .NET Core Application never copies this folders and files to bin output folder. They are copied when you Publish.

I just tested creating a new .NET Core Web Application (.NET Core) with a Web Application template from VS 2015, then I change framework from netcoreapp1.0 to net461, removed dependency to Microsoft.NETCore.App, added dependency to Microsoft.AspNetCore.Hosting.WindowsServices copy and paste the few lines needed to run as a service to Main method, it compiled and worked in Debug perfectly. I published it to a folder, install the service (sc create bla bla), run the service and everything worked perfectly!

Let me know if you experience any problem, but you should be able to convert to net461 without problems and run as a service. I just test it to be sure and it works as expected.

**Comment by oswaldofreitas** [comment]
I'll try again, but the problem is when I debug the project in VS 2015 and I got the browser error saying that Index.cshtml was not found.

**Comment by oswaldofreitas** [comment]
Am I missing something?

```
{
  "dependencies": {
    "NETStandard.Library": "1.6.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.0",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "BundlerMinifier.Core": "2.2.281",
    "Microsoft.AspNetCore.Hosting.WindowsServices": "1.0.0"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net461": {}
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "Areas/**/Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  },

  "runtimes": {
    "win7-x64": {}
  }
}
```

**Comment by gerardo-lijs** [comment]
I don't see any problem in your project.json file. As I said, I tried converting a simple new template Web Application from netcoreapp1.0 to net461 to check if maybe there was something broken there regarding Views and files and it worked for me. It debugged, compiled and even worked as a windows service without any problem. Let me know if you are able to resolve your issue.

**Comment by oswaldofreitas** [comment]
@gerardo-lijs I found the problem:

In your example you do this:

```
if (isConsole)
    contentPath = Path.GetDirectoryName(Process.GetCurrentProcess().MainModule.FileName);
else
{
    contentPath = Directory.GetCurrentDirectory();
}
```

What I did was only put a "!" before `isConsole`

Thank you very much for you help

**Comment by gerardo-lijs** [comment]
Glad it worked! I just check the code and it's the exact opposite of the one you have. Maybe when copy/pasting you inverted the values. I close this Issue now. I'm working on a few Windows Services controlled via Web API, with user auth, settings, log monitoring, etc. I think its really very useful. I will try to share more of this projects in the future. If time allows, a small Web API Framework to interact with Windows Services.

**Comment by oswaldofreitas** [comment]
Yep, tks for your concise and objective sample
